# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 696a13815c8255937cae8ffbe7f31db29b6e2768337766fb724ae46e31edbb78e287338565b17c4f4fa8fed173873e8b1a5ccfc11504f0fa2019a161fa4b9273

test:
  secret_key_base: 5a6b9c912d57d8930d64930b480b07276db11048542d6be4b01883f3f5cbc3864f17e88bf6c2b7387fe73137172a188408c8fd9b12b8816a68fd1a154d96a6e7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
